services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: tech!clin
    ports:
      - "5434:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - /minio_data:/data
    environment:
      - MINIO_ROOT_USER=tech_clin
      - MINIO_ROOT_PASSWORD=tech!clin
    command: server /data --console-address ":9001"
volumes:
  postgres-data:
